services:
  _defaults:
    autowire: true
    autoconfigure: true

  Krabo\IsotopeStockBundle\Controller\ProductController: ~
  Krabo\IsotopeStockBundle\Controller\BookingController: ~
  Krabo\IsotopeStockBundle\Controller\OverviewController: ~
  Krabo\IsotopeStockBundle\Cron\UpdateTstamp: ~
  Krabo\IsotopeStockBundle\EventListener\ProductListener:
    public: true
  Krabo\IsotopeStockBundle\EventListener\ProductCollectionListener:
    public: true